import glob

Import('env')

SConscript('#algorithm/sort/SConscript')
SConscript('#algorithm/search/SConscript')

needed_libs = [
        '#algorithm/sort/sort.a',
        '#algorithm/search/search.a',
        ]

env.Program('main',
        [
        '#algorithm/main.cc',
        needed_libs,
        ],
        )
