import glob

Import('env')

SConscript('#algorithm/sort/SConscript')

needed_libs = [
        '#algorithm/sort/sort.a'
        ]

env.Program('main',
        [
        '#algorithm/main.cc',
        needed_libs,
        ],
        )
